/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package br.com.victor.coke.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the UserCoke service. Represents a row in the &quot;Coke_UserCoke&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>br.com.victor.coke.model.impl.UserCokeModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>br.com.victor.coke.model.impl.UserCokeImpl</code>.
 * </p>
 *
 * @author victor
 * @see UserCoke
 * @generated
 */
@ProviderType
public interface UserCokeModel extends BaseModel<UserCoke> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a user coke model instance should use the {@link UserCoke} interface instead.
	 */

	/**
	 * Returns the primary key of this user coke.
	 *
	 * @return the primary key of this user coke
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this user coke.
	 *
	 * @param primaryKey the primary key of this user coke
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this user coke.
	 *
	 * @return the uuid of this user coke
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this user coke.
	 *
	 * @param uuid the uuid of this user coke
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the user coke ID of this user coke.
	 *
	 * @return the user coke ID of this user coke
	 */
	public long getUserCokeId();

	/**
	 * Sets the user coke ID of this user coke.
	 *
	 * @param userCokeId the user coke ID of this user coke
	 */
	public void setUserCokeId(long userCokeId);

	/**
	 * Returns the coke ID of this user coke.
	 *
	 * @return the coke ID of this user coke
	 */
	public long getCokeId();

	/**
	 * Sets the coke ID of this user coke.
	 *
	 * @param cokeId the coke ID of this user coke
	 */
	public void setCokeId(long cokeId);

	/**
	 * Returns the user ID of this user coke.
	 *
	 * @return the user ID of this user coke
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this user coke.
	 *
	 * @param userId the user ID of this user coke
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this user coke.
	 *
	 * @return the user uuid of this user coke
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this user coke.
	 *
	 * @param userUuid the user uuid of this user coke
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the position of this user coke.
	 *
	 * @return the position of this user coke
	 */
	@AutoEscape
	public String getPosition();

	/**
	 * Sets the position of this user coke.
	 *
	 * @param position the position of this user coke
	 */
	public void setPosition(String position);

	/**
	 * Returns the create date of this user coke.
	 *
	 * @return the create date of this user coke
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this user coke.
	 *
	 * @param createDate the create date of this user coke
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this user coke.
	 *
	 * @return the modified date of this user coke
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this user coke.
	 *
	 * @param modifiedDate the modified date of this user coke
	 */
	public void setModifiedDate(Date modifiedDate);

	@Override
	public UserCoke cloneWithOriginalValues();

}